# Generated by Django 5.2.4 on 2025-07-21 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planned', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_initiatives', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_business_initiatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Business Initiatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInitiativeProductInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_weight', models.DecimalField(blank=True, decimal_places=2, help_text='How much this product initiative contributes to the business initiative.', max_digits=5, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('business_initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_initiative_product_initiatives', to='roadmap.businessinitiative')),
            ],
            options={
                'ordering': ['business_initiative'],
            },
        ),
        migrations.CreateModel(
            name='BusinessKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower number = higher priority (e.g. 1 is highest)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_kpis', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_kpis', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'Business KPIs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower number = higher priority (e.g. 1 is highest)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_objectives', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_objectives', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'Business Objectives',
                'ordering': ['priority', 'deadline'],
            },
        ),
        migrations.CreateModel(
            name='BusinessObjectiveInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower number = higher priority for this objective')),
                ('confidence_level', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence in this initiative’s impact on the objective (e.g., 90%)', max_digits=5, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('business_initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.businessinitiative')),
                ('business_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.businessobjective')),
                ('contribution_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='common.contributiontype')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('business_objective', 'business_initiative')},
            },
        ),
        migrations.AddField(
            model_name='businessinitiative',
            name='business_objectives',
            field=models.ManyToManyField(blank=True, help_text='Business objectives this initiative contributes to.', related_name='business_initiatives', through='roadmap.BusinessObjectiveInitiative', to='roadmap.businessobjective'),
        ),
        migrations.CreateModel(
            name='BusinessObjectiveKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Relative weight or contribution % of this objective toward this KPI.', max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('business_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_objective_kpis', to='roadmap.businesskpi')),
                ('business_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_objective_kpis', to='roadmap.businessobjective')),
            ],
            options={
                'ordering': ['business_objective', 'business_kpi'],
                'unique_together': {('business_objective', 'business_kpi')},
            },
        ),
        migrations.AddField(
            model_name='businessobjective',
            name='business_kpis',
            field=models.ManyToManyField(related_name='business_objectives', through='roadmap.BusinessObjectiveKPI', to='roadmap.businesskpi'),
        ),
        migrations.CreateModel(
            name='CustomerObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('metric_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_objectives', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_objectives', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Customer Objective',
                'verbose_name_plural': 'Customer Objectives',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerObjectiveProductInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence (%) that this initiative contributes to the objective', max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('contribution_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_objective_initiatives', to='common.contributiontype')),
                ('customer_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.customerobjective')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('size_count', models.PositiveIntegerField(blank=True, help_text='Estimated number of customers in this segment', null=True)),
                ('size_value', models.FloatField(blank=True, help_text='Estimated total value of this customer segment', null=True)),
                ('strategic_importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Strategic importance of this segment to the organization', max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_segments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_segments', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Customer Segment',
                'verbose_name_plural': 'Customer Segments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customerobjective',
            name='customer_segments',
            field=models.ManyToManyField(blank=True, related_name='customer_objectives', to='roadmap.customersegment'),
        ),
        migrations.CreateModel(
            name='ProductInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planned', max_length=50)),
                ('business_initiatives', models.ManyToManyField(related_name='linked_product_initiatives', through='roadmap.BusinessInitiativeProductInitiative', to='roadmap.businessinitiative')),
                ('customer_objectives', models.ManyToManyField(related_name='linked_product_initiatives', through='roadmap.CustomerObjectiveProductInitiative', to='roadmap.customerobjective')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_initiatives', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_product_initiatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Initiatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customerobjectiveproductinitiative',
            name='product_initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.productinitiative'),
        ),
        migrations.AddField(
            model_name='businessinitiativeproductinitiative',
            name='product_initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.productinitiative'),
        ),
        migrations.CreateModel(
            name='ProductKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_kpis', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_kpis', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInitiativeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Relative weight or contribution % of this initiative toward this KPI.', max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('product_initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_initiative_kpis', to='roadmap.productinitiative')),
                ('product_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_initiative_kpis', to='roadmap.productkpi')),
            ],
            options={
                'unique_together': {('product_initiative', 'product_kpi')},
            },
        ),
        migrations.AddField(
            model_name='productinitiative',
            name='product_kpis',
            field=models.ManyToManyField(related_name='product_initiatives', through='roadmap.ProductInitiativeKPI', to='roadmap.productkpi'),
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prioritization_logic', models.TextField(blank=True, help_text='Explanation of prioritization logic used (e.g. RICE, Value/Effort, WSJF, etc.)')),
                ('time_horizon', models.CharField(choices=[('short_term', 'Short Term (0-3 months)'), ('medium_term', 'Medium Term (3-6 months)'), ('long_term', 'Long Term (6+ months)')], default='short_term', help_text='Time horizon this roadmap covers', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roadmaps', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_score', models.FloatField(blank=True, help_text='Calculated priority score for this initiative in this specific roadmap.', null=True)),
                ('priority_rank', models.PositiveIntegerField(blank=True, help_text='Rank of this initiative within the roadmap (1 = highest priority), based on priority_score.', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('product_initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_entries', to='roadmap.productinitiative')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_entries', to='roadmap.roadmap')),
            ],
            options={
                'ordering': ['priority_rank', 'priority_score'],
                'unique_together': {('roadmap', 'product_initiative')},
            },
        ),
        migrations.AddField(
            model_name='roadmap',
            name='product_initiatives',
            field=models.ManyToManyField(related_name='included_in_roadmaps', through='roadmap.RoadmapEntry', to='roadmap.productinitiative'),
        ),
        migrations.AlterUniqueTogether(
            name='customerobjectiveproductinitiative',
            unique_together={('customer_objective', 'product_initiative')},
        ),
        migrations.AlterUniqueTogether(
            name='businessinitiativeproductinitiative',
            unique_together={('business_initiative', 'product_initiative')},
        ),
    ]
