# Generated by Django 5.2.4 on 2025-07-11 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='planned', max_length=50)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_initiatives', to='accounts.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_product_initiatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Product Initiatives',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_kpis', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductInitiativeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Relative weight or contribution % of this initiative toward this KPI.', max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('product_initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.productinitiative')),
                ('product_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.productkpi')),
            ],
            options={
                'unique_together': {('product_initiative', 'product_kpi')},
            },
        ),
        migrations.AddField(
            model_name='productinitiative',
            name='kpis',
            field=models.ManyToManyField(related_name='initiatives', through='roadmap.ProductInitiativeKPI', to='roadmap.productkpi'),
        ),
    ]
