# Generated by Django 5.2.4 on 2025-07-29 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('roadmap', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productinitiativekpi',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_initiative_kpis', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='productinitiativekpi',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_product_initiative_kpis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerobjectiveproductinitiative',
            name='customer_objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_objective_product_initiatives', to='roadmap.customerobjective'),
        ),
        migrations.AlterField(
            model_name='customerobjectiveproductinitiative',
            name='product_initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_objective_product_initiatives', to='roadmap.productinitiative'),
        ),
    ]
