# Generated by Django 5.2.4 on 2025-07-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_businessinitiative'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInitiativeProductInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_weight', models.DecimalField(blank=True, decimal_places=2, help_text='How much this product initiative contributes to the business initiative.', max_digits=5, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('business_initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.businessinitiative')),
                ('product_initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.productinitiative')),
            ],
            options={
                'ordering': ['business_initiative'],
                'unique_together': {('business_initiative', 'product_initiative')},
            },
        ),
        migrations.AddField(
            model_name='businessinitiative',
            name='product_initiatives',
            field=models.ManyToManyField(related_name='business_initiatives', through='roadmap.BusinessInitiativeProductInitiative', to='roadmap.productinitiative'),
        ),
    ]
