# Generated by Django 5.2.4 on 2025-08-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_departments_organization_headcount_and_more'),
        ('roadmap', '0002_productinitiativekpi_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinitiative',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='accounts.product'),
        ),
    ]
