# Generated by Django 5.2.4 on 2025-08-23 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_departments_organization_headcount_and_more'),
        ('roadmap', '0003_productinitiative_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinitiative',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='accounts.product'),
            preserve_default=False,
        ),
    ]
