# Generated by Django 5.2.4 on 2025-07-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0004_businesskpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInitiativeKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_weight', models.DecimalField(blank=True, decimal_places=2, help_text='Relative weight or impact this initiative has on the KPI.', max_digits=5, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('business_initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.businessinitiative')),
                ('business_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.businesskpi')),
            ],
            options={
                'ordering': ['business_initiative'],
                'unique_together': {('business_initiative', 'business_kpi')},
            },
        ),
        migrations.AddField(
            model_name='businessinitiative',
            name='business_kpis',
            field=models.ManyToManyField(related_name='business_initiatives', through='roadmap.BusinessInitiativeKPI', to='roadmap.businesskpi'),
        ),
    ]
