# Generated by Django 5.2.4 on 2025-07-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0006_businessobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesskpi',
            name='priority',
            field=models.PositiveSmallIntegerField(default=1, help_text='Lower number = higher priority (e.g. 1 is highest)'),
        ),
        migrations.CreateModel(
            name='BusinessObjectiveInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Lower number = higher priority for this objective')),
                ('type_of_contribution', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect'), ('enabling', 'Enabling')], default='direct', max_length=50)),
                ('confidence_level', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence in this initiative’s impact on the objective (e.g., 90%)', max_digits=5, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('business_initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.businessinitiative')),
                ('business_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.businessobjective')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('business_objective', 'business_initiative')},
            },
        ),
        migrations.AddField(
            model_name='businessinitiative',
            name='business_objectives',
            field=models.ManyToManyField(blank=True, help_text='Business objectives this initiative contributes to.', related_name='business_initiatives', through='roadmap.BusinessObjectiveInitiative', to='roadmap.businessobjective'),
        ),
    ]
