# Generated by Django 5.2.4 on 2025-07-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('roadmap', '0008_customersegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('metric_name', models.CharField(blank=True, max_length=255, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_segments', models.ManyToManyField(blank=True, related_name='customer_objectives', to='roadmap.customersegment')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_objectives', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerObjectiveInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('discovery', 'Discovery'), ('conversion', 'Conversion'), ('retention', 'Retention'), ('satisfaction', 'Satisfaction')], default='discovery', max_length=50)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence (%) that this initiative contributes to the objective', max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('customer_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.customerobjective')),
                ('product_initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadmap.productinitiative')),
            ],
            options={
                'unique_together': {('customer_objective', 'product_initiative')},
            },
        ),
        migrations.AddField(
            model_name='customerobjective',
            name='product_initiatives',
            field=models.ManyToManyField(related_name='customer_objectives', through='roadmap.CustomerObjectiveInitiative', to='roadmap.productinitiative'),
        ),
    ]
