# Generated by Django 5.2.4 on 2025-07-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('roadmap', '0009_customerobjective_customerobjectiveinitiative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerobjectiveinitiative',
            name='contribution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_objective_initiatives', to='common.contributiontype'),
        ),
    ]
