# Generated by Django 5.2.4 on 2025-07-12 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('roadmap', '0010_alter_customerobjectiveinitiative_contribution_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessobjectiveinitiative',
            name='type_of_contribution',
        ),
        migrations.AddField(
            model_name='businessobjectiveinitiative',
            name='contribution_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='common.contributiontype'),
        ),
    ]
