# Generated by Django 5.2.4 on 2025-07-13 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('roadmap', '0011_remove_businessobjectiveinitiative_type_of_contribution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerobjective',
            options={'ordering': ['name'], 'verbose_name': 'Customer Objective', 'verbose_name_plural': 'Customer Objectives'},
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prioritization_logic', models.TextField(blank=True, help_text='Explanation of prioritization logic used (e.g. RICE, Value/Effort)')),
                ('is_active', models.BooleanField(default=True)),
                ('business_initiatives', models.ManyToManyField(blank=True, related_name='roadmaps', to='roadmap.businessinitiative')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roadmaps', to=settings.AUTH_USER_MODEL)),
                ('customer_objectives', models.ManyToManyField(blank=True, related_name='roadmaps', to='roadmap.customerobjective')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='accounts.organization')),
                ('product_initiatives', models.ManyToManyField(blank=True, related_name='roadmaps', to='roadmap.productinitiative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
