# Generated by Django 5.2.4 on 2025-07-21 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('roadmap', '0012_alter_customerobjective_options_roadmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerObjectiveInitiative',
            new_name='CustomerObjectiveProductInitiative',
        ),
        migrations.RemoveField(
            model_name='businessinitiative',
            name='business_kpis',
        ),
        migrations.RemoveField(
            model_name='businessinitiative',
            name='product_initiatives',
        ),
        migrations.RemoveField(
            model_name='customerobjective',
            name='product_initiatives',
        ),
        migrations.RemoveField(
            model_name='productinitiative',
            name='kpis',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='business_initiatives',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='customer_objectives',
        ),
        migrations.AddField(
            model_name='customerobjective',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_objectives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productinitiative',
            name='business_initiatives',
            field=models.ManyToManyField(related_name='linked_product_initiatives', through='roadmap.BusinessInitiativeProductInitiative', to='roadmap.businessinitiative'),
        ),
        migrations.AddField(
            model_name='productinitiative',
            name='customer_objectives',
            field=models.ManyToManyField(related_name='linked_product_initiatives', through='roadmap.CustomerObjectiveProductInitiative', to='roadmap.customerobjective'),
        ),
        migrations.AddField(
            model_name='productinitiative',
            name='product_kpis',
            field=models.ManyToManyField(related_name='product_initiatives', through='roadmap.ProductInitiativeKPI', to='roadmap.productkpi'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='time_horizon',
            field=models.CharField(choices=[('short_term', 'Short Term (0-3 months)'), ('medium_term', 'Medium Term (3-6 months)'), ('long_term', 'Long Term (6+ months)')], default='short_term', help_text='Time horizon this roadmap covers', max_length=100),
        ),
        migrations.AlterField(
            model_name='businessinitiativeproductinitiative',
            name='business_initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_initiative_product_initiatives', to='roadmap.businessinitiative'),
        ),
        migrations.AlterField(
            model_name='productinitiativekpi',
            name='product_initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_initiative_kpis', to='roadmap.productinitiative'),
        ),
        migrations.AlterField(
            model_name='productinitiativekpi',
            name='product_kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_initiative_kpis', to='roadmap.productkpi'),
        ),
        migrations.AlterField(
            model_name='productkpi',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_kpis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='prioritization_logic',
            field=models.TextField(blank=True, help_text='Explanation of prioritization logic used (e.g. RICE, Value/Effort, WSJF, etc.)'),
        ),
        migrations.CreateModel(
            name='BusinessObjectiveKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Relative weight or contribution % of this objective toward this KPI.', max_digits=5, null=True)),
                ('note', models.TextField(blank=True)),
                ('business_kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_objective_kpis', to='roadmap.businesskpi')),
                ('business_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_objective_kpis', to='roadmap.businessobjective')),
            ],
            options={
                'ordering': ['business_objective', 'business_kpi'],
                'unique_together': {('business_objective', 'business_kpi')},
            },
        ),
        migrations.AddField(
            model_name='businessobjective',
            name='business_kpis',
            field=models.ManyToManyField(related_name='business_objectives', through='roadmap.BusinessObjectiveKPI', to='roadmap.businesskpi'),
        ),
        migrations.CreateModel(
            name='RoadmapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_score', models.FloatField(blank=True, help_text='Calculated priority score for this initiative in this specific roadmap.', null=True)),
                ('priority_rank', models.PositiveIntegerField(blank=True, help_text='Rank of this initiative within the roadmap (1 = highest priority), based on priority_score.', null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('product_initiative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_entries', to='roadmap.productinitiative')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_entries', to='roadmap.roadmap')),
            ],
            options={
                'ordering': ['priority_rank', 'priority_score'],
                'unique_together': {('roadmap', 'product_initiative')},
            },
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='product_initiatives',
            field=models.ManyToManyField(related_name='included_in_roadmaps', through='roadmap.RoadmapEntry', to='roadmap.productinitiative'),
        ),
        migrations.DeleteModel(
            name='BusinessInitiativeKPI',
        ),
    ]
