# Generated by Django 5.2.4 on 2025-07-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0013_rename_customerobjectiveinitiative_customerobjectiveproductinitiative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='product_initiatives',
        ),
    ]
