# Generated by Django 5.2.4 on 2025-07-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0014_remove_roadmap_product_initiatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='product_initiatives',
            field=models.ManyToManyField(related_name='included_in_roadmaps', through='roadmap.RoadmapEntry', to='roadmap.productinitiative'),
        ),
    ]
