# Generated by Django 5.2.4 on 2025-08-12 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('needs_review', 'Needs Review'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('run_type', models.CharField(blank=True, choices=[('doc_parse', 'Document Parsing'), ('roadmap_gen', 'Roadmap Generation'), ('entity_extract', 'Entity Extraction'), ('strategic_analysis', 'Strategic Analysis')], max_length=20, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_node', models.CharField(blank=True, default='', max_length=100)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brain_runs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brain_runs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrainRunEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('node_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('validation', 'Validation'), ('error', 'Error'), ('info', 'Info')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='brain.brainrun')),
            ],
            options={
                'ordering': ['run', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='brainrun',
            index=models.Index(fields=['organization', 'status'], name='brain_brain_organiz_a4377a_idx'),
        ),
        migrations.AddIndex(
            model_name='brainrun',
            index=models.Index(fields=['created_by'], name='brain_brain_created_1888e8_idx'),
        ),
        migrations.AddIndex(
            model_name='brainrun',
            index=models.Index(fields=['created_at'], name='brain_brain_created_644f79_idx'),
        ),
        migrations.AddIndex(
            model_name='brainrun',
            index=models.Index(fields=['run_type', 'status'], name='brain_brain_run_typ_070135_idx'),
        ),
        migrations.AddIndex(
            model_name='brainrunevent',
            index=models.Index(fields=['run', 'seq'], name='brain_brain_run_id_2d0dee_idx'),
        ),
        migrations.AddIndex(
            model_name='brainrunevent',
            index=models.Index(fields=['node_name'], name='brain_brain_node_na_b07b59_idx'),
        ),
        migrations.AddIndex(
            model_name='brainrunevent',
            index=models.Index(fields=['event_type'], name='brain_brain_event_t_356564_idx'),
        ),
        migrations.AddIndex(
            model_name='brainrunevent',
            index=models.Index(fields=['created_at'], name='brain_brain_created_27d7be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='brainrunevent',
            unique_together={('run', 'seq')},
        ),
    ]
