# Generated by Django 5.2.4 on 2025-08-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='departments',
            field=models.CharField(blank=True, help_text='Comma-separated list of departments', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='headcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='markets',
            field=models.CharField(blank=True, help_text='Comma-separated list of markets', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.organization')),
            ],
        ),
    ]
